### ISSUE TITLE
panic: runtime error: index out of range [4] with length 4

### ISSUE THREAD

**Issue by pirracas77** [erkexzcx/valetudopng#12]
**Describe the bug**

From time to time, valetudopng stops working and  this error it is showed.

`Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: 2024/04/04 09:38:36 [MQTT consumer] Connected
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: 2024/04/04 09:38:36 [MQTT consumer] Subscribed to map data topic
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: 2024/04/04 09:38:36 [MQTT producer] Connected
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: panic: runtime error: index out of range [4] with length 4
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: goroutine 1 [running]:
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: github.com/erkexzcx/valetudopng/pkg/renderer.(*valetudoImage).findFourColors(0xc0000ce120)
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: #011/home/runner/work/valetudopng/valetudopng/pkg/renderer/fourcolortheorem.go:97 +0x1c9
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: github.com/erkexzcx/valetudopng/pkg/renderer.newValetudoImage(0xc000064240, 0xc00002e2a0)
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: #011/home/runner/work/valetudopng/valetudopng/pkg/renderer/drawer.go:78 +0x47b
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: github.com/erkexzcx/valetudopng/pkg/renderer.(*Renderer).Render(0xc17bb422d74ba398?, {0xc0004a2000?, 0xbba6a0?, 0x37e11d600?}, 0xfffffffc8d40c5e5?)
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: #011/home/runner/work/valetudopng/valetudopng/pkg/renderer/renderer.go:58 +0x3d
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: github.com/erkexzcx/valetudopng/pkg/server.Start(0xc0000100f0)
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: #011/home/runner/work/valetudopng/valetudopng/pkg/server/server.go:54 +0x3e5
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: main.main()
Apr  4 09:38:36 jeedom valetudopng_v1.0.16_linux_amd64[6525]: #011/home/runner/work/valetudopng/valetudopng/cmd/valetudopng/main.go:32 +0xd4
Apr  4 09:38:36 jeedom systemd[1]: valetudopng_viomi.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr  4 09:38:36 jeedom systemd[1]: valetudopng_viomi.service: Failed with result 'exit-code'.
`

**To Reproduce**

run valetudopng and see the log

**Expected behavior**

the valetudopng keeps up an runnign

**Screenshots/Outputs**

see the log above

**JSON**
If you believe the issue is related to JSON parsing (map data from Vacuum) - you can speed up this issue and provide us a contents (or relevant part) of `http://<robot_ip>/api/v2/robot/state` here. **Note** that this data contains your house map.

**Comment by erkexzcx** [comment]
Hi. Is this happening with the latest version? Please try [v1.0.16](https://github.com/erkexzcx/valetudopng/releases/tag/v1.0.16) and let me know if it works fine.

Additionally, please note that I no longer have Roborock Vacuum and I cannot test or troubleshoot this issue at all, so community help is needed here...

**Comment by pirracas77** [comment]
> Hi. Is this happening with the latest version? Please try [v1.0.16](https://github.com/erkexzcx/valetudopng/releases/tag/v1.0.16) and let me know if it works fine.
> 
> Additionally, please note that I no longer have Roborock Vacuum and I cannot test or troubleshoot this issue at all, so community help is needed here...

yes, you can see in the logs the binary used : valetudopng_v1.0.16_linux_amd64[6525

**Comment by pirracas77** [comment]
I have upgraded to last version:

`/home/valetudopng# ./valetudopng_v1.0.17_linux_amd64 --version
Version: v1.0.17
`
But the error in logs is still present.
What kind of help do you need in order to have more information about this error ?
